Cambios en scripts para que se puedan correr desde cualquier carpeta

diff --git a/bootstrap/config b/bootstrap/config
--- a/bootstrap/config
+++ b/bootstrap/config
@@ -18,6 +18,21 @@ echo -e $G_COL$CONS_DIV"\n\n **Config script for Red-Social-Asociacion**\n\n"$CO
 
 #-----------------------------------------#
 
+#----------------------------------------#
+
+# Getting in the right location
+
+MY_PATH="`dirname \"$0\"`" 
+MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
+if [ -z "$MY_PATH" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo -e $R_COL"Please verify permissions on bootstrap folder!\n"$DEF_COL
+  exit 1  # fail
+fi
+cd "$MY_PATH"
+
+
 #-----------------------------------------#
 # Configure Neo4J Server
 echo -e $G_COL"Configuring Neo4J Server...\n"$DEF_COL
diff --git a/bootstrap/setup b/bootstrap/setup
--- a/bootstrap/setup
+++ b/bootstrap/setup
@@ -31,6 +31,20 @@ function loggerRed {
 
 #----------------------------------------#
 
+# Getting in the right location
+
+MY_PATH="`dirname \"$0\"`" 
+MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
+if [ -z "$MY_PATH" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  loggerRed "Please verify permissions on bootstrap folder!\n"
+  exit 1  # fail
+fi
+cd "$MY_PATH"
+
+#----------------------------------------#
+
 # Clean log file
 echo "" > $LOG_FILE
 
@@ -134,18 +148,70 @@ cd bootstrap
 loggerGreen "Installing service start and shutdown scripts...\n"
 
 echo "#!/bin/bash
+#----------------------------------------#
+
+# Getting in the right location
+
+MY_PATH=\"`dirname \\"$0\\"`\" 
+MY_PATH=\"`( cd \\"$MY_PATH\\" && pwd )`\"  # absolutized and normalized
+if [ -z \"$MY_PATH\" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo \"Please verify permissions on folder!\n\"
+  exit 1  # fail
+fi
+cd \"$MY_PATH\"
 ./neo4j-community-$NEO4J_VER/bin/neo4j start -server -Xmx512M -XX:+UseConcMarkSweepGC" > $BIN_DIR/neoRun
 chmod +x $BIN_DIR/neoRun
 
 echo "#!/bin/bash
+#----------------------------------------#
+
+# Getting in the right location
+
+MY_PATH=\"`dirname \\"$0\\"`\" 
+MY_PATH=\"`( cd \\"$MY_PATH\\" && pwd )`\"  # absolutized and normalized
+if [ -z \"$MY_PATH\" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo \"Please verify permissions on folder!\n\"
+  exit 1  # fail
+fi
+cd \"$MY_PATH\"
 ./neo4j-community-$NEO4J_VER/bin/neo4j stop" > $BIN_DIR/neoStop
 chmod +x $BIN_DIR/neoStop
 
 echo "#!/bin/bash
+#----------------------------------------#
+
+# Getting in the right location
+
+MY_PATH=\"`dirname \\"$0\\"`\" 
+MY_PATH=\"`( cd \\"$MY_PATH\\" && pwd )`\"  # absolutized and normalized
+if [ -z \"$MY_PATH\" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo \"Please verify permissions on folder!\n\"
+  exit 1  # fail
+fi
+cd \"$MY_PATH\"
 ./mongodb/mongodb-linux-x86_64-$MONGODB_VER/bin/mongod --dbpath ./mongodata/db/" > $BIN_DIR/mongoRun
 chmod +x $BIN_DIR/mongoRun
 
 echo "#!/bin/bash
+#----------------------------------------#
+
+# Getting in the right location
+
+MY_PATH=\"`dirname \\"$0\\"`\" 
+MY_PATH=\"`( cd \\"$MY_PATH\\" && pwd )`\"  # absolutized and normalized
+if [ -z \"$MY_PATH\" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo \"Please verify permissions on folder!\n\"
+  exit 1  # fail
+fi
+cd \"$MY_PATH\"
 ./mongodb/mongodb-linux-x86_64-$MONGODB_VER/bin/mongod --shutdown --dbpath mongodata/db" > $BIN_DIR/mongoStop
 chmod +x $BIN_DIR/mongoStop
 
