correccion setup

diff --git a/bootstrap/setup b/bootstrap/setup
--- a/bootstrap/setup
+++ b/bootstrap/setup
@@ -94,11 +94,14 @@ loggerGreen "Dependencies OK!\n"
 #-----------------------------------------#
 # Stop Neo4J Server
 
-STATUS=`./$NEO4J_DIR/bin/neo4j status`
-if [[ $STATUS != *"not"* ]]
+if [ -d "./$NEO4J_DIR/bin" ]
 then
-    loggerGreen "Stopping Neo4J Server...\n"
-	./$BIN_DIR/neoStop >/dev/null 2>&1 || { loggerRed "Error stopping Neo4J Server!\n"; exit 1; }
+	STATUS=`./$NEO4J_DIR/bin/neo4j status`
+	if [[ $STATUS != *"not"* ]]
+	then
+		loggerGreen "Stopping Neo4J Server...\n"
+		./$BIN_DIR/neoStop >/dev/null 2>&1 || { loggerRed "Error stopping Neo4J Server!\n"; exit 1; }
+	fi
 fi
 
 #----------------------------------------#
